### ISSUE TITLE
Authentication of Publisher

### ISSUE THREAD

**Issue by jimsch** [EricssonResearch/coap-pubsub-profile#1]
If you want to have authentication, then steps 2 requires that step 1 be done first.  THe publisher will need to have an auth token from AS1 in order to register an asymmetric key with AS2.

**Comment by fpalombini** [comment]
(very delayed response, sorry about that)

Step 2 is token-less, as specified in [Section 3.1](https://ericssonresearch.github.io/coap-pubsub-profile/draft-palombini-ace-coap-pubsub-profile.html#rfc.section.3.1). It does need to include the publisher's public key, but that's it. Do you see a problem with that?
